=== KockataEPich/Stendhal/data/conf/achievements.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="stendhal"
	xmlns:tns="http://www.example.org/zones" elementFormDefault="qualified"
	xmlns:Q1="stendhal">

	<element name="achievements" type="Q1:achievementGroup"></element>

	<complexType name="achievementGroup">
		<sequence>
			<element name="achievement" type="Q1:achievementType" minOccurs="0"
				maxOccurs="unbounded"></element>
		</sequence>
	</complexType>

	<complexType name="achievementType">
		<sequence>
			<element name="identifier" type="string" />
			<element name="title" type="string"></element>
			<!--finish the category-->
			<element name="category" type="Q1:Category"  minOccurs="0" maxOccurs="1"></element>
			<element name="description" type="xsd:string"></element>
			<element name="score" type="xsd:decimal"></element>
			<element name="active" type="boolean"></element>
			<!--FInish the chat condition-->
			<element name="condition" type="Q1:ChatCondition"></element>
		</sequence>
		<!--Should attribute name be included-->
		<!--attribute name="name" type="string" use="required"></attribute-->
	</complexType>
	<!--FInish here, should they even be here?-->
	<complexType name="Category">
		<xsd:enumeration value = "EXPERIENCE"/>
		<xsd:enumeration value = "FIGHTING"/>
		<xsd:enumeration value = "QUEST"/>
		<xsd:enumeration value = "OUTSIDE_ZONE"/>
		<xsd:enumeration value = "UNDERGROUND_ZONE"/>
		<xsd:enumeration value = "INTERIOR_ZONE"/>
		<xsd:enumeration value = "AGE"/>
		<xsd:enumeration value = "ITEM"/>
		<xsd:enumeration value = "OBTAIN"/>
		<xsd:enumeration value = "FRIEND"/>
		<xsd:enumeration value = "PRODUCTION"/>
		<xsd:enumeration value = "QUEST_ADOS_ITEMS"/>
		<xsd:enumeration value = "QUEST_SEMOS_MONSTER"/>
		<xsd:enumeration value = "QUEST_KIRDNEH_ITEM"/>
		<xsd:enumeration value = "QUEST_MITHRILBOURGH_ENEMY_ARMY"/>
	</complexType>

	<complexType name="ChatCondition">
		<sequence>
			<element name="questname" type="xsd:string"/>
			<element name="index" type="xsd:decimal"/>
			<element name="expectedSmallerValue" type="xsd:decimal"/>
		</sequence>
		<attribute name="class-name" type="string"/>
	</complexType>
	
</schema>

=== KockataEPich/Stendhal/data/conf/achievements/experience.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">
	
  <achievement>
    <identifier>"xp.level.010"</identifier>
    <title>"Greenhorn"</title>
    <category>
      <enumeration>EXPERIENCE</enumeration>
    </category>
    <description>"Reach level 10"</description>
    <score>1</score>
    <active>true</active>
    <condition>
     <expectedSmallerValue>9</expectedSmallerValue>
    </condition>
  </achievement>
  
  <achievement>
    <identifier>"xp.level.050"</identifier>
    <title>"Novice"</title>
    <category>
      <enumeration>EXPERIENCE</enumeration>
    </category>
    <description>"Reach level 50"</description>
    <score>1</score>
    <active>true</active>
    <condition>
     <expectedSmallerValue>49</expectedSmallerValue>
    </condition>
  </achievement>
  
  
  <achievement>
    <identifier>"xp.level.100"</identifier>
    <title>"Apprentice"</title>
    <category>
      <enumeration>EXPERIENCE</enumeration>
    </category>
    <description>"Reach level 100"</description>
    <score>1</score>
    <active>true</active>
    <condition>
     <expectedSmallerValue>99</expectedSmallerValue>
    </condition>
  </achievement>
  
  <achievement>
    <identifier>"xp.level.200"</identifier>
    <title>"Adventurer"</title>
    <category>
      <enumeration>EXPERIENCE</enumeration>
    </category>
    <description>"Reach level 300"</description>
    <score>2</score>
    <active>true</active>
    <condition>
     <expectedSmallerValue>299</expectedSmallerValue>
    </condition>
  </achievement>
  
  <achievement>
    <identifier>"xp.level.300"</identifier>
    <title>"Experienced Adventurer"</title>
    <category>
      <enumeration>EXPERIENCE</enumeration>
    </category>
    <description>"Reach level 400"</description>
    <score>2</score>
    <active>true</active>
    <condition>
     <expectedSmallerValue>399</expectedSmallerValue>
    </condition>
  </achievement>
  
  <achievement>
    <identifier>"xp.level.400"</identifier>
    <title>"Master Adventurer"</title>
    <category>
      <enumeration>EXPERIENCE</enumeration>
    </category>
    <description>"Reach level 400"</description>
    <score>2</score>
    <active>true</active>
    <condition>
     <expectedSmallerValue>399</expectedSmallerValue>
    </condition>
  </achievement>
  
  <achievement>
    <identifier>"xp.level.500"</identifier>
    <title>"Stendhal Master"</title>
    <category>
      <enumeration>EXPERIENCE</enumeration>
    </category>
    <description>"Reach level 500"</description>
    <score>5</score>
    <active>true</active>
    <condition>
     <expectedSmallerValue>499</expectedSmallerValue>
    </condition>
  </achievement>
  
												
  <achievement>
    <identifier>"xp.level.597"</identifier>
    <title>"Stendhal High Master"</title>
    <category>
      <enumeration>EXPERIENCE</enumeration>
    </category>
    <description>"Reach level 597"</description>
    <score>5</score>
    <active>true</active>
    <condition>
     <expectedSmallerValue>596</expectedSmallerValue>
    </condition>
  </achievement>
  


</achievements>

=== KockataEPich/Stendhal/data/conf/achievements/adosItemQuest.xml
<?xml version="1.0" encoding="UTF-8"?>
<achievements xmlns="stendhal" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="stendhal ../achievements.xsd ">

  <achievement>
    <identifier>"quest.special.daily_item.0010"</identifier>
    <title>"Ados' Supporter"</title>
    <category>
      <enumeration>QUEST_ADOS_ITEMS</enumeration>
    </category>
    <description>"Finish daily item quest 10 times"</description>
    <score>1</score>
    <active>true</active>
    <condition>
     <questname>"daily_item"</questname>
     <index>2</index>
     <expectedSmallerValue>9</expectedSmallerValue>
    </condition>
  </achievement>
  
  <achievement>
    <identifier>"quest.special.daily_item.0050"</identifier>
    <title>"Ados' Provider"</title>
    <category>
      <enumeration>QUEST_ADOS_ITEMS</enumeration>
    </category>
    <description>"Finish daily item quest 50 times"</description>
    <score>1</score>
    <active>true</active>
    <condition>
     <questname>"daily_item"</questname>
     <index>2</index>
     <expectedSmallerValue>49</expectedSmallerValue>
    </condition>
  </achievement>
  
  <achievement>
    <identifier>"quest.special.daily_item.0100"</identifier>
    <title>"Ados' Supplier"</title>
    <category>
      <enumeration>QUEST_ADOS_ITEMS</enumeration>
    </category>
    <description>"Finish daily item quest 100 times"</description>
    <score>2</score>
    <active>true</active>
    <condition>
     <questname>"daily_item"</questname>
     <index>2</index>
     <expectedSmallerValue>99</expectedSmallerValue>
    </condition>
  </achievement>
  
  <achievement>
    <identifier>"quest.special.daily_item.250"</identifier>
    <title>"Ados' Stockpiler"</title>
    <category>
      <enumeration>QUEST_ADOS_ITEMS</enumeration>
    </category>
    <description>"Finish daily item quest 250 times"</description>
    <score>2</score>
    <active>true</active>
    <condition>
     <questname>"daily_item"</questname>
     <index>2</index>
     <expectedSmallerValue>249</expectedSmallerValue>
    </condition>
  </achievement>
  
  <achievement>
    <identifier>"quest.special.daily_item.500"</identifier>
    <title>"Ados' Hoarder"</title>
    <category>
      <enumeration>QUEST_ADOS_ITEMS</enumeration>
    </category>
    <description>"Finish daily item quest 500 times"</description>
    <score>5</score>
    <active>true</active>
    <condition>
     <questname>"daily_item"</questname>
     <index>2</index>
     <expectedSmallerValue>499</expectedSmallerValue>
    </condition>
  </achievement>


</achievements>
